---
version: '2'

services:
  postgres:
    image: postgres:9.6.19-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: root
    volumes:
    - ./files/postgres:/docker-entrypoint-initdb.d