server:
  port: 9081
  

spring:
  kafka:
    bootstrap-servers: "172.28.163.44:9092"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema: 
          registry:
            url: "http://172.28.163.44:8081"

  profiles:
     active: dev
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/root
    username: root
    password: secret
     
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    
avro:
  topic:
    name: "claseFinalV1"   