/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.demo.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class StockHistory extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4849992509759808745L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StockHistory\",\"namespace\":\"com.example.demo.schema\",\"fields\":[{\"name\":\"studentId\",\"type\":\"int\",\"default\":-1},{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lastName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"mLastName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"updated_at\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StockHistory> ENCODER =
      new BinaryMessageEncoder<StockHistory>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StockHistory> DECODER =
      new BinaryMessageDecoder<StockHistory>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<StockHistory> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<StockHistory> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<StockHistory>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this StockHistory to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a StockHistory from a ByteBuffer. */
  public static StockHistory fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int studentId;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence lastName;
  @Deprecated public java.lang.CharSequence mLastName;
  @Deprecated public java.lang.CharSequence updated_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StockHistory() {}

  /**
   * All-args constructor.
   * @param studentId The new value for studentId
   * @param name The new value for name
   * @param lastName The new value for lastName
   * @param mLastName The new value for mLastName
   * @param updated_at The new value for updated_at
   */
  public StockHistory(java.lang.Integer studentId, java.lang.CharSequence name, java.lang.CharSequence lastName, java.lang.CharSequence mLastName, java.lang.CharSequence updated_at) {
    this.studentId = studentId;
    this.name = name;
    this.lastName = lastName;
    this.mLastName = mLastName;
    this.updated_at = updated_at;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return studentId;
    case 1: return name;
    case 2: return lastName;
    case 3: return mLastName;
    case 4: return updated_at;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: studentId = (java.lang.Integer)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: lastName = (java.lang.CharSequence)value$; break;
    case 3: mLastName = (java.lang.CharSequence)value$; break;
    case 4: updated_at = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'studentId' field.
   * @return The value of the 'studentId' field.
   */
  public java.lang.Integer getStudentId() {
    return studentId;
  }

  /**
   * Sets the value of the 'studentId' field.
   * @param value the value to set.
   */
  public void setStudentId(java.lang.Integer value) {
    this.studentId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'mLastName' field.
   * @return The value of the 'mLastName' field.
   */
  public java.lang.CharSequence getMLastName() {
    return mLastName;
  }

  /**
   * Sets the value of the 'mLastName' field.
   * @param value the value to set.
   */
  public void setMLastName(java.lang.CharSequence value) {
    this.mLastName = value;
  }

  /**
   * Gets the value of the 'updated_at' field.
   * @return The value of the 'updated_at' field.
   */
  public java.lang.CharSequence getUpdatedAt() {
    return updated_at;
  }

  /**
   * Sets the value of the 'updated_at' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(java.lang.CharSequence value) {
    this.updated_at = value;
  }

  /**
   * Creates a new StockHistory RecordBuilder.
   * @return A new StockHistory RecordBuilder
   */
  public static com.example.demo.schema.StockHistory.Builder newBuilder() {
    return new com.example.demo.schema.StockHistory.Builder();
  }

  /**
   * Creates a new StockHistory RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StockHistory RecordBuilder
   */
  public static com.example.demo.schema.StockHistory.Builder newBuilder(com.example.demo.schema.StockHistory.Builder other) {
    return new com.example.demo.schema.StockHistory.Builder(other);
  }

  /**
   * Creates a new StockHistory RecordBuilder by copying an existing StockHistory instance.
   * @param other The existing instance to copy.
   * @return A new StockHistory RecordBuilder
   */
  public static com.example.demo.schema.StockHistory.Builder newBuilder(com.example.demo.schema.StockHistory other) {
    return new com.example.demo.schema.StockHistory.Builder(other);
  }

  /**
   * RecordBuilder for StockHistory instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StockHistory>
    implements org.apache.avro.data.RecordBuilder<StockHistory> {

    private int studentId;
    private java.lang.CharSequence name;
    private java.lang.CharSequence lastName;
    private java.lang.CharSequence mLastName;
    private java.lang.CharSequence updated_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.demo.schema.StockHistory.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.studentId)) {
        this.studentId = data().deepCopy(fields()[0].schema(), other.studentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.mLastName)) {
        this.mLastName = data().deepCopy(fields()[3].schema(), other.mLastName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.updated_at)) {
        this.updated_at = data().deepCopy(fields()[4].schema(), other.updated_at);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing StockHistory instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.demo.schema.StockHistory other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.studentId)) {
        this.studentId = data().deepCopy(fields()[0].schema(), other.studentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.mLastName)) {
        this.mLastName = data().deepCopy(fields()[3].schema(), other.mLastName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.updated_at)) {
        this.updated_at = data().deepCopy(fields()[4].schema(), other.updated_at);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'studentId' field.
      * @return The value.
      */
    public java.lang.Integer getStudentId() {
      return studentId;
    }

    /**
      * Sets the value of the 'studentId' field.
      * @param value The value of 'studentId'.
      * @return This builder.
      */
    public com.example.demo.schema.StockHistory.Builder setStudentId(int value) {
      validate(fields()[0], value);
      this.studentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'studentId' field has been set.
      * @return True if the 'studentId' field has been set, false otherwise.
      */
    public boolean hasStudentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'studentId' field.
      * @return This builder.
      */
    public com.example.demo.schema.StockHistory.Builder clearStudentId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.example.demo.schema.StockHistory.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.example.demo.schema.StockHistory.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }

    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.example.demo.schema.StockHistory.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.lastName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.example.demo.schema.StockHistory.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'mLastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getMLastName() {
      return mLastName;
    }

    /**
      * Sets the value of the 'mLastName' field.
      * @param value The value of 'mLastName'.
      * @return This builder.
      */
    public com.example.demo.schema.StockHistory.Builder setMLastName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.mLastName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'mLastName' field has been set.
      * @return True if the 'mLastName' field has been set, false otherwise.
      */
    public boolean hasMLastName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'mLastName' field.
      * @return This builder.
      */
    public com.example.demo.schema.StockHistory.Builder clearMLastName() {
      mLastName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'updated_at' field.
      * @return The value.
      */
    public java.lang.CharSequence getUpdatedAt() {
      return updated_at;
    }

    /**
      * Sets the value of the 'updated_at' field.
      * @param value The value of 'updated_at'.
      * @return This builder.
      */
    public com.example.demo.schema.StockHistory.Builder setUpdatedAt(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.updated_at = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'updated_at' field has been set.
      * @return True if the 'updated_at' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'updated_at' field.
      * @return This builder.
      */
    public com.example.demo.schema.StockHistory.Builder clearUpdatedAt() {
      updated_at = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StockHistory build() {
      try {
        StockHistory record = new StockHistory();
        record.studentId = fieldSetFlags()[0] ? this.studentId : (java.lang.Integer) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.lastName = fieldSetFlags()[2] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.mLastName = fieldSetFlags()[3] ? this.mLastName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.updated_at = fieldSetFlags()[4] ? this.updated_at : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StockHistory>
    WRITER$ = (org.apache.avro.io.DatumWriter<StockHistory>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StockHistory>
    READER$ = (org.apache.avro.io.DatumReader<StockHistory>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
